# Generated by Django 5.2.17 on 2026-08-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='api_keys',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='delivery_partners_config',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='email_providers_config',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='payment_gateways_config',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='sms_providers_config',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='third_party_providers_config',
        ),
        migrations.AddField(
            model_name='tenant',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tenant_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='is_primary',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
